config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "recipes#index"
  resources :recipes do
    resources :comments, only: :create
      collection do
        get 'search'
      end
      collection do
        get 'research'
      end
  end
  resources :users, only: [:show, :new, :index]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  belongs_to :time_require
  has_many_attached :images
  has_many :comments
  has_many :recipe_tag_relations, dependent: :destroy
  has_many :tags, through: :recipe_tag_relations
  has_many :likes


  with_options presence: true do
    validates :category_id, numericality: { other_than: 0 } 
    validates :time_require_id, numericality: { other_than: 0, message: "can't be blank" }
    validates :title
    validates :material
    validates :text
    validates :images
  end

  def self.research(research)
    if research != ""
      Recipe.joins(:tags).where('tags.name LIKE ?',  "%#{research}%")
    else
      Recipe.all
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :move_to_index, except:[:index]

  def index
    @recipes = Recipe.order('created_at DESC')
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    params[:recipe][:name].split(',')
    tags = params[:recipe][:name].split(" ")
    tags = tags.map do |tag|
    # tag.where(name: tag).first_or_initialize
    end
    # if @recipe.valid? & params[:recipe][:name].presence
    
    tag = Tag.where(name: params[:recipe][:name]).first_or_initialize

    if @recipe.valid? & tag.valid?
      @recipe.save
      tag.save

      RecipeTagRelation.create(recipe_id: @recipe.id, tag_id: tag.id)
      return redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comment = Comment.new
    @comments = @recipe.comments.includes(:user)
  end

  def edit
    @recipe = Recipe.find(params[:id])
    redirect_to root_path unless current_user.id == @recipe.user_id
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    if @recipe.save
      redirect_to recipe_path
    else
      render :edit
    end
  end

  def destroy
    @recipes = Recipe.all
    @recipe = @recipes.find(params[:id])
    if @recipe.destroy
      redirect_to root_path
    end
  end

  def research
    @recipes = Recipe.research(params[:keyword])
   end

  def search
    return nil if params[:keyword] == ""
    tag = Tag.where(['name LIKE ?', "%#{params[:keyword]}%"])
    render json:{ keyword: tag }
  end


  private

  def recipe_params
    params.require(:recipe).permit(:title, :material, :text, :category_id, :time_require_id, :recipe_id, images: []).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, local: true do |f| %>

<div class="field_type">

<div class="field">
  <div class="field_image">

    <%= f.label :images, "料理の画像", class:'recipe_text' %><br />
    <%= f.file_field :images, name: 'recipe[images][]', id:"cook_image" %>
      <div id="image-list"></div>

    <% @recipe.images.each do |image| %>
      <%= image_tag image, class:'images' %>
    <% end %>

  </div>
</div>


<div class="active-hash">
  <div class="field">
    <div class="field_time_require">
      <div class="recipe_text">
        所要時間<br/>
      </div>
      <%= f.collection_select(:time_require_id, TimeRequire.all, :id, :name, {}, {class:"collection-select"}) %>
    </div>
  </div>

  <div class="field">
    <div class="field_category">
      <div class="recipe_text">
        カテゴリー<br/>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"collection-select"}) %>
    </div>
  </div>
</div>

<div class="field">
  <div class="tag-field", id='tag-field'>
    <%= f.label :name, "タグ""(複数入力の際はカンマで区切って入力ください)", class:"tag-name" %><br />
    <%= f.text_field :name,  placeholder: "#時短レシピ, #サラダ", class:"input-tag" %>
  </div>
    <div id="search-result">
    </div>
</div>

<div class="field">
  <div class="field_title">
    <%= f.label :title, "料理名", class:"recipe-title" %><br />
    <%= f.text_field :title, id:"cook_title", class:"title_field" %>
  </div>
</div>

<div class="field">
  <div class="field_material">
    <%= f.label :material, "材料", class:"recipe-materials" %><br />
    <%= f.text_area :material, id:"cook_material", placeholder:"鶏肉◯g・醤油 大さじ１・ニンニク一欠片 等", class:"material_field" %>
  </div>
</div>

<div class="field">
  <div class="field_text">
    <%= f.label :text, "調理方法", class:"way_to_cook" %><br />
    <%= f.text_area :text, id:"cook_text", placeholder:"調味料は全て合わせておく...", class:"text_field" %>
  </div>
</div>

  <div class="actions">
    <%= f.submit "シェアする", class: :form__btn %>
    <% end %>
  </div>
</div>

app/views/recipes/_like.html.erb
<% if current_user.liked_by?(@recipe.id) %>
  <div class="favo">
    <%= link_to destroy_like_path(@recipe), class: :"like_link", method: :DELETE, remote: true do %>
      <i class="fa fa-heart unlike-btn"></i>
    <% end %>
    <%= @recipe.likes.count %>
  </div>
<% else %>
  <div class="l_favorite">
    <%= link_to create_like_path(@recipe), class: :"like-link", method: :POST, remote: true do %>
      <i class="fa fa-heart like-btn"></i>
    <% end %>
    <%= @recipe.likes.count %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
        
        <div class="recipe-image-content">
          <% recipe.images.find do |image| %>
            <div class="research-list">
              <%= image_tag image, class:"recipe-images" %>
          <% end %>
            <div class="top-icon">
              <i class="fa fa-heart like__btn"></i>
                <div class="count">
                  <%= recipe.likes.count %>
                </div>
            </div>
        </div>

        <div class="over-view">
          <div class="recipe-title">
            <h3 class="recipe-title">
              <%= recipe.title %>
            </h3>
          </div>

          <h3 class="recipe-category">
            <%= recipe.category.name %>
          </h3>
          <h3 class="time_require">
            <%= recipe.time_require.name %>
          </h3>
            </div>
        </div>

app/views/recipes/edit.html.erb
<div class="main">
  <div class="inner">
    <h2 class="new-recipe"></h2>
        <%= render partial: "form", locals:{recipe: @recipe} %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="main-container">

  <div class="top-page">
    <div class="main-logo">
      <%= image_tag("/assets/hotcake.jpeg", class:"main-image")%>
    </div>

    <div class="second-main-logo">
      <h1>コンカツ</h1>
      <h2><span>コンカツとは...</span>&emsp;献立活動のこと。<br/>
      なにか作って食べたいけど、時間もないし、めんどくさい。そんな忙しい毎日を頑張るあなたへ<br/>
      みんなのお家から、お手軽レシピを発信します</h2>
    </div>
  </div>

    <div class="popular-tags">
      <div class='search-bar-contents'>
        <%= form_with(url: research_recipes_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "ズボラ飯", class: "sbox" %>
          <%= form.submit "検索", class: "sbtn" %>
        <% end %>
      </div>
    </div>

<div class="recipe__content">
  <div class="subtitle">
  新着レシピ
  </div>
  <div class="recipe-contents">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe.id) do %>
        <div class="recipes__list">
          <%= render partial:"recipe", locals: {recipe: recipe} %>
        </div>
      <% end %>

    <% end %>
  </div>
</div>
</div>

app/views/recipes/new.html.erb
<div class="main">

  <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  
  <div class="inner">
    <h2 class="new-recipe">新しいレシピを投稿する</h2>
    <%= render partial:"form" %>
  </div>
</div>

app/views/recipes/research.html.erb
<div class="research-list">

  <div class="research-bar">
    <%= form_with(url: research_recipes_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "ズボラ飯", class: "sbox" %>
      <%= form.submit "検索", class: "sbtn" %>
    <% end %>
  </div>

  <div class="contents-row">
  
  <% if @recipes.length == 0 %>
    <div class="nil_message">ヒットする投稿は0件です</div>
  <% end %>

    <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe.id) do %>
        <%= render partial: "recipe", locals: { recipe: recipe } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class ="main">
  <div class="top-title">
      <div class="hedding">
        <p class="recipe__time__require">所要時間 : 
          <%= @recipe.time_require.name %>
        </p>
        <p class="recipe__category">カテゴリー : 
          <%= @recipe.category.name %>
        </p>
      </div>

      <ul class="tag">
        <li class="tag-list">
          <% @recipe.tags.each do |tag| %>
            <%= "#{tag.name}" %>
          <%end%>
        </li>
      </ul>
      <p class="show__hedding">
        <%= @recipe.title %>
      </p>

      <div class="likes">
        <div id="recipe_<%= @recipe.id %>">
          <%= render partial:"like" %>
        </div>
      </div>

      <div class="recipe__user">
        <%= link_to "Posted by  #{@recipe.user.nickname}", user_path(@recipe.user_id), class: :recipe_user_btn %>
      </div>
        <% if user_signed_in? && current_user.id == @recipe.user.id %>
          <div class="btn__display">
            <%= link_to "編集", edit_recipe_path(@recipe.id), method: :get, class: :edit__btn %>
            <%= link_to "削除", recipe_path(@recipe.id), method: :delete, class: :delete__btn %>
          </div>
        <% end %>
  </div>

      <div class="separate__main">
        <div class="recipe__image">
          <% @recipe.images.each do |image| %>
            <%= image_tag image, class:'images' %>
          <% end %>
        </div>

        <div class="recipe__body">
          <div class="recipe__materials">
           <p class="recipe__material">材料</p>
            <div class="materials">
              <%= @recipe.material %>
            </div>
          </div>
          <div class="description">
            <p class="recipe__description">調理方法</p>
              <div class="description_area">
                <%= safe_join(@recipe.text.split("\n"),tag(:br)) %>
              </div>
          </div>
        </div>

      </div>

    <div class="comment__container">
      <% if user_signed_in? %>
        <%= form_with(model: [@recipe, @comment], local: false) do |f| %>
          <%= f.text_area :comment, placeholder: "コメントする", rows: "2", class: "comment-form" %>
          <%= f.submit '送信', id: "comment_submit" %>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>

        <div class="comments" id="comments">
          <h4>＜コメント一覧＞</h4>
            <div class="comment_list">
              <% @comments.each do |comment| %>
                <%= render partial: "comments/comment", locals: {comment: comment} %>
              <% end %>
            </div>
        </div>
    </div>

</div>